### ISSUE TITLE
Today's Widget not Updating until opening the app

### ISSUE THREAD

**Issue by faberthemaster** [cpvbruno/Cardapio-iOS#1]
After day starts a new cycle, today's widget does not update for the current day.

Scenario:
- App was **not** in execution (foreground) at the time;
- App was **not** running in background;
- Internet connection was **available** and stable;
- App running last version from TestFlight (1.1.3 (4))

**Comment by cpvbruno** [comment]
@faberthemaster fixed Today's View and also Complete Notifications, now available on #3 
Soon on 1.1.3(5) at TestFlight

**Comment by faberthemaster** [comment]
Tested, working flawlessly
