### ISSUE TITLE
Fade animation when swiping between dates is inverted

### ISSUE THREAD

**Issue by faberthemaster** [cpvbruno/Cardapio-iOS#15]
On the app, when swiping from one day to another, there is a fade animation... The animation is going from not visible to visible, I think it should be the opposite, from visible to not visible.

Scenario:
- Swipe from one day to another;
- Check the fade animation during the process;
- Notice that when the animation starts, the list is completely gone and when it finishes, it shows all the items from the menu.

**Comment by cpvbruno** [comment]
I removed the fade animation, It looks better without it, I will let you know when is available for testing

**Comment by cpvbruno** [comment]
The behavior changed
