### ISSUE TITLE
[Watch] App is not updating to reflect current menu

### ISSUE THREAD

**Issue by faberthemaster** [cpvbruno/Cardapio-iOS#2]
Apple Watch app is not updating with what is shown on the phone app, the date is showing as the current date, although, the app is showing the menu from last day. Should I manually tap "Update" on the Watch app everyday to see the current menu?

Scenario:
- Watch **is** connected to the phone;
- Phone **has** internet connectivity;
- Phone has **only** watch connected via Bluetooth;
- Watch app **was** running in background.

Check screenshot for references:

![img_6183](https://cloud.githubusercontent.com/assets/11094971/23993865/0d212c6e-0a21-11e7-8c33-a9452f3cd46e.PNG)

![img_6184](https://cloud.githubusercontent.com/assets/11094971/23993868/0eab6c20-0a21-11e7-87aa-f35d1eb402d8.PNG)

**Comment by cpvbruno** [comment]
I will Remove the feature and schedule for a future release, will now focus on Notifications and Today View

**Comment by cpvbruno** [comment]
fixed
